//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensTracker.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
