//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpensTracker.DAL.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ExpenseTrackerEntities : DbContext
    {
        public ExpenseTrackerEntities()
            : base("name=ExpenseTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ExpenseLimits> ExpenseLimits { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<p_get_expense_count_Result> p_get_expense_count(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_get_expense_count_Result>("p_get_expense_count", userIdParameter);
        }
    
        public virtual ObjectResult<p_get_totalamount_by_date_Result> p_get_totalamount_by_date(Nullable<int> createBy)
        {
            var createByParameter = createBy.HasValue ?
                new ObjectParameter("createBy", createBy) :
                new ObjectParameter("createBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_get_totalamount_by_date_Result>("p_get_totalamount_by_date", createByParameter);
        }
    
        public virtual ObjectResult<p_get_most_expensed_category_Result> p_get_most_expensed_category(Nullable<int> createdBy)
        {
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_get_most_expensed_category_Result>("p_get_most_expensed_category", createdByParameter);
        }
    }
}
